# config for gitpod
tasks:
  - name: 'main'
    init: |
      (
        set -e
        gp sync-await setup_complete
        bash ./util/main.sh
      )
  - name: 'setup'
    init: |
      (
        set -e
        bash ./util/setup.sh
        gp sync-done setup_complete
      )
