# config for gitpod
tasks:
  - name: 'main'
    init: |
      (
        set -e
        gp sync-await setup_complete
        gp tasks stop "$( gp tasks list --no-color | grep 'setup' | awk '{print $2}' )"
        bash ./util/main.sh
      )
  - name: 'setup'
    init: |
      (
        set -e
        bash ./util/setup.sh
        gp sync-done setup_complete
        exit
      )
vscode:
    extensions:
        - nomicfoundation.hardhat-solidity
